version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sppass
    ports: 
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql